# Generated by Django 4.2.6 on 2023-10-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('HARD', 'Hard')], default='Beginner', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
