# Generated by Django 4.2.6 on 2023-11-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
    ]
