# Generated by Django 4.2.6 on 2023-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='no_picture.jpg', upload_to='books'),
        ),
    ]
