# Generated by Django 4.2.6 on 2023-11-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hc', 'Hard cover'), ('eb', 'E-Book'), ('ab', 'Audiobook')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('cl', 'Classic'), ('ro', 'Romantic'), ('co', 'Comedy'), ('fa', 'Fantasy'), ('ho', 'Horror'), ('ed', 'Educational')], default='cl', max_length=12),
        ),
    ]
