# Generated by Django 4.2.2 on 2023-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='genre',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('entree', 'Entree'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
